pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                echo 'Hello Worl  d from date '
                echo "Running ${env.BUILD_ID} on  ${env.JENKINS_URL}"
                echo "Node Name ${NODE_NAME} workspace ${WORKSPACE}"

            }
        }
    }
}