import java.text.SimpleDateFormat
import java.text.ParseException;  
import java.text.SimpleDateFormat;  
import java.util.Date;  
import java.util.Locale;




    def sdf = new SimpleDateFormat('dd-MM-yyyy')
    def dateDefaultValue = sdf.format(new Date().plusDays(2))
    def day = dateDefaultValue.plus(1)
    def date = new Date();  
    def strDate = formatter.format(date);  

pipeline {
    agent any
    parameters {
        string(
            name: 'SOMEDATE',
            defaultValue: "${dateDefaultValue}",
            description: 'Default value is current date in the format YYYYmmdd',
            trim: true
        )
    }
    stages {
        stage('Example') {
            steps {
                echo "Hello Worl  d from date ${env.SOMEDATE}"
                echo "------- ${day}"
                echo "Running ${env.BUILD_ID} on  ${env.JENKINS_URL}"
                echo "Node Name ${NODE_NAME} workspace ${WORKSPACE}"
            }
        }
    }
}
